# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Farsight App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Farsight App
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'Farsight AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Farsight AppUITests' do
    # Pods for testing
  end

end
