# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Farsight App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FarSight
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'IQKeyboardManagerSwift'
  pod 'YPImagePicker'
  pod 'KMPlaceholderTextView', '~> 1.4.0'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'FontAwesome.swift'
  pod 'SDWebImage'
  
end
